---
- name: Write nginx balancer conf
  template:
    src: balancer.conf.j2
    dest: /etc/nginx/conf.d/balancer.conf

- name: Rewrite standard nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Reload nginx
...
